name: pandas-scipy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.6
  - numpy=1.14.5
  - pandas=0.23.1
  - matplotlib=2.2.2
  - seaborn=0.8.1
  - ipython=6.4.0
  - jupyter=1.0.0
  - notebook=5.5.0
  - dask=0.18.1
  - distributed=1.22.0
  - toolz=0.9.0
  - pandas-datareader=0.6.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - statsmodels=0.9.0
  - xlrd=1.1.0
  - pip:
    - lifetimes==0.6.0.0
